#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=10gb
#PBS -m a
#PBS -l feature='intel16'


# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission


#Starting in GBS/ProcessRadtags/Indicies

source ~/.bash_profile

module load bowtie2/2.2.6
module load picardTools/1.89


if [ "$PBS_JOBNAME" == "notset" ]
  then
  echo "please set the job name"
  exit 1
fi

cd ${PBS_O_WORKDIR} || exit

bowtie2-build ${genome} ${PBS_JOBNAME} #build index

# also build dictionary for GATK

java -jar $PICARD/CreateSequenceDictionary.jar R=${genome} O=`basename ${genome} .fasta`.dict

# and a fasta index

samtools faidx ${genome}
