#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=20,walltime=04:00:00,mem=64gb
#PBS -m a
#PBS -l feature='intel16'

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated)
# -t 0-? : job numbers for array submission


source ~/.bash_profile


module load freebayes/1.0.2
module load Trimmomatic/0.33
module load bwa/0.7.12.r1044
module load vcftools/0.1.14
module load seqtk/1.0
module load CDHIT/4.6.1
module load vcflib/20140522
module load gparallel/20131022
module load BAMTools/2.2.3
module load PEAR/0.9.6

alias pearRM='pear'

cd ${PBS_O_WORKDIR} || exit

dDocent config.file